### ISSUE TITLE
Not supporting different encoding.

### ISSUE THREAD

**Issue by DJArty** [APerricone/vscode-dbf#2]
![2021-01-21_14-08](https://user-images.githubusercontent.com/9507282/105349254-1ce64b80-5bf2-11eb-9a5f-15b0c567ef62.png)
Looks like not supporting different encoding - only win1255 or utf8?  Need more: IBM866, DOS... etc. 
Now see empty table with moving blue line.. 
Maybe godbf project can help with it.

**Comment by APerricone** [comment]
Hello, can you send me a example dbf ?

**Comment by DJArty** [comment]
Hello!
test dbf and view into zip
And may be help this  http://dbf-software.com/dbf-file-encoding.html
and this https://github.com/LindsayBradford/go-dbf
  
>Четверг, 21 января 2021, 16:49 +02:00 от Antonino Perricone <notifications@github.com>:
> 
> 
>Hello, can you send me a example dbf ?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
DJ Arty

**Comment by APerricone** [comment]
can you send me the zip to my email, antonino.perricone@yahoo.it ?
can you try last version also?

**Comment by APerricone** [comment]
There is no information about the code page or encoding used inside the dbf, you see it correctly on DBFNavigator because it uses the codepage of the system, in your case cp866. 
From v.0.0.7 this extension uses the setting "files.encoding" to decode the dbf file, I added a setting "dbf-table.encoding" also, to allow different encoding for text and dbf.

**Comment by DJArty** [comment]
> uses the setting "files.encoding"

Thank you! Now its cool.

**Comment by DJArty** [comment]
Hello!
Can you check this example file? 
Structure same like before, but not show anything is VSCode.
  
>Четверг, 21 января 2021, 16:49 +02:00 от Antonino Perricone <notifications@github.com>:
> 
> 
>Hello, can you send me a example dbf ?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
DJ Arty

**Comment by APerricone** [comment]
jut this morning, testing the old sample I saw an error, are you trying the  0.1.1 ?

**Comment by APerricone** [comment]
no, the last version does not open it, how did you do it?

**Comment by DJArty** [comment]
Yes,  v0.1.1
First sample work, second sample — dont work — blue vertical line move from left to right and not show data.
  
>Вторник, 16 февраля 2021, 12:27 +02:00 от Antonino Perricone <notifications@github.com>:
> 
> 
>no, the last version does not open it, how did you do it?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
DJ Arty

**Comment by DJArty** [comment]
codepage Cyrillic cp866 first example — ok, second — not
VSCode from snap for Ubuntu 
>Вторник, 16 февраля 2021, 12:27 +02:00 от Antonino Perricone <notifications@github.com>:
> 
> 
>no, the last version does not open it, how did you do it?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
DJ Arty

**Comment by DJArty** [comment]
Ok, I see diffs in structure
PRKRKVVALT ( D :8)    — first sample
PRKRKVVALT ( T :8)    — second

  
>Вторник, 16 февраля 2021, 12:27 +02:00 от Antonino Perricone <notifications@github.com>:
> 
> 
>no, the last version does not open it, how did you do it?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
DJ Arty

**Comment by DJArty** [comment]
PRKRKVVALT ( T : 5 )    — second     (Date Time — type of field) — think this is problem.

  
>Вторник, 16 февраля 2021, 14:27 +02:00 от DJ Arty <dj_arty@mail.ru>:
> 
>Ok, I see diffs in structure
>PRKRKVVALT ( D :8)    — first sample
>PRKRKVVALT ( T :8)    — second
>
> 
>>Вторник, 16 февраля 2021, 12:27 +02:00 от Antonino Perricone < notifications@github.com >:
>> 
>> 
>>no, the last version does not open it, how did you do it?
>>—
>>You are receiving this because you authored the thread.
>>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
> 
> 
>DJ Arty
>  
 
 
DJ Arty

**Comment by APerricone** [comment]
correct, the problem is that field T:5 , I am based on [harbour](https://github.com/harbour/core) code and that case is not contempled. did you do it with Fox Pro? Can you send me an example with different values on time?

**Comment by DJArty** [comment]
My dbf is export file from accounting program.
So may be export engine have some error — really strange to see length 5 in date/time. 
If try to open dbf in LibreOffice or Fox Pro — can see empty field but formatted like datetime  __/__/__/ __:__AM
May be later try to play with FoxPro and make real datetime field example. (many export format type for dbf)  
  
>Вторник, 16 февраля 2021, 14:38 +02:00 от Antonino Perricone <notifications@github.com>:
> 
> 
>correct, the problem is that field T:5 , I am based on  harbour code and that case is not contempled. did you do it with Fox Pro? Can you send me an example with different values on time?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
DJ Arty

**Comment by DJArty** [comment]
My dbf is export file from accounting program.
So may be export engine have some error — really strange to see length 5 in date/time. 
If try to open dbf in LibreOffice or Fox Pro — can see empty field but formatted like datetime  __/__/__/ __:__AM
May be later try to play with FoxPro and make real datetime field example. (many export format type for dbf)  
>Вторник, 16 февраля 2021, 14:38 +02:00 от Antonino Perricone <notifications@github.com>:
> 
> 
>correct, the problem is that field T:5 , I am based on  harbour code and that case is not contempled. did you do it with Fox Pro? Can you send me an example with different values on time?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
DJ Arty

**Comment by APerricone** [comment]
The column type T: 5 is filled with "0000 " (with a space at end), I added some code that if the data is in this form it parse it, but I am not sure that it parse them in the correct way, I think the correct values are between 0000 and 2359 like hours and minutes.
Now I see it in this way:
![image](https://user-images.githubusercontent.com/22457168/108082945-de1da700-7072-11eb-9dcc-5d5173330a23.png)
